import { Router } from 'express';
import { getAddresses, createAddress, updateAddress, deleteAddress, setDefaultAddress } from '../controllers/addressController';
import { authenticate } from '../middleware/authMiddleware';
import { validateBody } from '../middleware/validator';
import { addressMutationSchema, updateAddressSchema } from '../validators/orderValidator';
const router = Router();
router.use(authenticate);
router.get('/', getAddresses);
router.post('/', validateBody(addressMutationSchema), createAddress);
router.put('/:id', validateBody(updateAddressSchema), updateAddress);
router.delete('/:id', deleteAddress);
router.patch('/:id/default', setDefaultAddress);
export default router;
