import { Router } from 'express';
import { getCategories, getCategoryById, createCategory, updateCategory, deleteCategory } from '../controllers/categoryController';
import { authenticate, requireRole } from '../middleware/authMiddleware';
import { validateBody } from '../middleware/validator';
import { categorySchema, updateCategorySchema } from '../validators/categoryValidator';
const router = Router();
router.get('/', getCategories);
router.get('/:id', getCategoryById);
router.post('/', authenticate, requireRole('ADMIN'), validateBody(categorySchema), createCategory);
router.put('/:id', authenticate, requireRole('ADMIN'), validateBody(updateCategorySchema), updateCategory);
router.delete('/:id', authenticate, requireRole('ADMIN'), deleteCategory);
export default router;
